name: ali_cloudapi_sign
description: ali_cloudapi_sign is package that sign aliyun api gateway request header,easy to use.

version: 1.0.10

homepage: https://github.com/csdntm/ali_cloudapi_sign

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.3

dev_dependencies:
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  test: ^1.15.2
